#ifndef __DEF__DEF
#define __DEF__DEF
#pragma once

#define __DEFAULT__WINDOW__WIDTH 640
#define __DEFAULT__WINDOW__HEIGHT 480

#define __DEFAULT__FRAME__PER__SECOND 60
#define __DEFAULT__NUM__INPUT 4
#define __DEFAULT__NUM__HIDDEN 1

#define __DEFAULT__NEURONS__HIDDEN__LAYER 10
#define __DEFAULT__NUM__OUTPUT 2
#define __DEFAULT__ACTIVATION__RESPONSE 1
#define __DEFAULT__BIAS -1

#define __DEFAULT__TURNRATE__MAX 0.3
#define __DEFAULT__SPEED__MAX 2

#define __DEFAULT__SCALE__SWEEPERS 5
#define __DEFAULT__SCALE__MINE 2 

#define __DEFAULT__NUM__SWEEPERS 30
#define __DEFAULT__NUM__MINES 40

#define __DEFAULT__TICKS__MAX 2000

#define __DEFAULT__CROSSOVER__RATE 0.7
#define __DEFAULT__MUTATION__RATE 0.1

#define __DEFAULT__PERTURBATION__MAX 0.3
#define __DEFAULT__NUM__ELITES 4
#define __DEFAULT__NUM__COPIES__ELITE 1
#endif // __DEF__DEF
